spring:
  application:
    name: product-service
  threads:
    virtual:
      enabled: true
  cloud:
    stream:
      function:
        definition: userActivityProducer
      bindings:
        userActivityProducer-out-0:
          destination: user-activities
          content-type: application/json


      kafka:
        binder:
          broker: localhost:9092
